spring:
  profiles:
    active: production
    include:
      - movies
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    properties:
      hibernate:
        type: trace
  data:
    rest:
      basePath: /api
logging:
  level:
    #root: INFO overrides logback
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql: trace
management:
  endpoint:
    health:
      show-details: "ALWAYS"
intValue: 0
